export const COMPANY_SECTOR: Record<string, string> = {
  Apple:                  'Consumer Tech',
  TSMC:                   'Semiconductors',
  ASML:                   'Semiconductors',
  Qualcomm:               'Semiconductors',
  Broadcom:               'Semiconductors',
  Samsung:                'Semiconductors',
  Nvidia:                 'Semiconductors',
  CRUS:                   'Semiconductors',
  SWKS:                   'Semiconductors',
  QRVO:                   'Semiconductors',
  AMKR:                   'Semiconductors',
  LRCX:                   'Semiconductors',
  ENTG:                   'Semiconductors',
  GlobalFoundries:        'Semiconductors',
  ADI:                    'Semiconductors',
  MCHP:                   'Semiconductors',
  'NXP Semiconductors':   'Semiconductors',
  'Analog Devices':       'Semiconductors',
  'Microchip Technology': 'Semiconductors',
  'Marvell Technology':   'Semiconductors',
  'Monolithic Power':     'Semiconductors',
  'Texas Instruments':    'Semiconductors',
  'ON Semiconductor':     'Semiconductors',
  Wolfspeed:              'Semiconductors',
  'Applied Materials':    'Semiconductors',
  'Lam Research':         'Semiconductors',
  Boeing:                 'Aerospace',
  'Spirit AeroSystems':   'Aerospace',
  Airbus:                 'Aerospace',
  RTX:                    'Aerospace',
  DCO:                    'Aerospace',
  HXL:                    'Aerospace',
  'Lockheed Martin':      'Aerospace',
  'General Dynamics':     'Aerospace',
  Textron:                'Aerospace',
  GKN:                    'Aerospace',
  'Triumph Group':        'Aerospace',
  GE:                     'Industrials',
  Honeywell:              'Industrials',
  Albemarle:              'Industrials',
  'TE Connectivity':      'Industrials',
  Amazon:                 'E-commerce',
  Meta:                   'E-commerce',
  Google:                 'E-commerce',
  Microsoft:              'E-commerce',
  UPS:                    'Logistics',
  FedEx:                  'Logistics',
  Tesla:                  'Automotive',
  Ford:                   'Automotive',
  GM:                     'Automotive',
  'LG Energy Solution':   'Automotive',
  Volkswagen:             'Automotive',
  Stellantis:             'Automotive',
  Autoliv:                'Automotive',
  BWA:                    'Automotive',
  APTV:                   'Automotive',
  Panasonic:              'Automotive',
  CATL:                   'Automotive',
  'Samsung SDI':          'Automotive',
  Toyota:                 'Automotive',
  BYD:                    'Automotive',
  CLS:                    'Tech',
  IBM:                    'Tech',
  Dell:                   'Tech',
  HPE:                    'Tech',
  'Super Micro':          'Tech',
  'Arista Networks':      'Tech',
}

export const SECTOR_COLORS: Record<string, string> = {
  'Consumer Tech': '#f472b6',  // pink
  Semiconductors:  '#a78bfa',  // violet
  Aerospace:       '#38bdf8',  // sky blue
  'E-commerce':    '#facc15',  // yellow
  Logistics:       '#34d399',  // emerald
  Automotive:      '#f87171',  // red
  Tech:            '#fb923c',  // orange
  Industrials:     '#a3e635',  // lime
}

export const SECTOR_ORDER = [
  'Consumer Tech', 'Semiconductors', 'Aerospace',
  'E-commerce', 'Logistics', 'Automotive', 'Tech', 'Industrials',
]

export const COMPANY_TICKER: Record<string, string> = {
  Apple:                  'AAPL',
  TSMC:                   'TSM',
  ASML:                   'ASML',
  Qualcomm:               'QCOM',
  Broadcom:               'AVGO',
  Samsung:                'SSNLF',
  Nvidia:                 'NVDA',
  CRUS:                   'CRUS',
  SWKS:                   'SWKS',
  QRVO:                   'QRVO',
  AMKR:                   'AMKR',
  LRCX:                   'LRCX',
  ENTG:                   'ENTG',
  GlobalFoundries:        'GFS',
  ADI:                    'ADI',
  MCHP:                   'MCHP',
  'NXP Semiconductors':   'NXPI',
  'Analog Devices':       'ADI',
  'Microchip Technology': 'MCHP',
  'Marvell Technology':   'MRVL',
  'Monolithic Power':     'MPWR',
  'Texas Instruments':    'TXN',
  'ON Semiconductor':     'ON',
  Wolfspeed:              'WOLF',
  'Applied Materials':    'AMAT',
  'Lam Research':         'LRCX',
  Boeing:                 'BA',
  'Spirit AeroSystems':   'SPR',
  Airbus:                 'EADSY',
  RTX:                    'RTX',
  DCO:                    'DCO',
  HXL:                    'HXL',
  'Lockheed Martin':      'LMT',
  'General Dynamics':     'GD',
  Textron:                'TXT',
  'Triumph Group':        'TGI',
  GE:                     'GE',
  Honeywell:              'HON',
  Albemarle:              'ALB',
  'TE Connectivity':      'TEL',
  Amazon:                 'AMZN',
  Meta:                   'META',
  Google:                 'GOOGL',
  Microsoft:              'MSFT',
  UPS:                    'UPS',
  FedEx:                  'FDX',
  Tesla:                  'TSLA',
  Ford:                   'F',
  GM:                     'GM',
  Volkswagen:             'VWAGY',
  Stellantis:             'STLA',
  Autoliv:                'ALV',
  BWA:                    'BWA',
  APTV:                   'APTV',
  Panasonic:              'PCRFY',
  Toyota:                 'TM',
  BYD:                    'BYDDY',
  CLS:                    'CLS',
  IBM:                    'IBM',
  Dell:                   'DELL',
  HPE:                    'HPE',
  'Super Micro':          'SMCI',
  'Arista Networks':      'ANET',
}

export function sectorColor(company: string): string {
  const s = COMPANY_SECTOR[company]
  return s ? (SECTOR_COLORS[s] ?? '') : ''
}

export function sectorBadge(company: string): { sector: string; color: string } | null {
  const sector = COMPANY_SECTOR[company]
  if (!sector) return null
  return { sector, color: SECTOR_COLORS[sector] ?? '#71717a' }
}
